name: Deploy Preview Redesign

on:
  push:
    branches:
      - docs/redesign-v2

concurrency: preview-redesign-${{ github.ref }}

jobs:
  deploy-redesign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/workflows/actions/turbo

      - name: Build
        run: pnpm build --cache-dir=.turbo --filter documentation-redesign
        env:
          FIGMA_API_TOKEN: ${{ secrets.FIGMA_API_TOKEN }}
          CSC: ${{ secrets.READ_CSC_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        id: publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --message documentation-redesign --filter documentation-redesign --alias documentation-redesign
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
